import type { Contract, ElementInfo } from '../../src/testing/uiContract';

/** An element as seen across all states of all flows of one page. */
export interface SeenElement {
  info: ElementInfo; // facts from the first state it was seen in
  states: string[]; // "flow#state" for every state it was seen in
  repeated?: { keys: (string | null)[]; names: string[] }; // merged over all states
}

/** Union of every element seen in any state of any flow, keyed by testId (first-seen order). */
export function collectElements(flows: Contract[]): Map<string, SeenElement> {
  const elements = new Map<string, SeenElement>();
  for (const flow of flows) {
    for (const step of flow.steps) {
      if (step.type !== 'state') continue;
      for (const e of step.elements) {
        if (!e.testId) continue;
        let seen = elements.get(e.testId);
        if (!seen) elements.set(e.testId, (seen = { info: e, states: [] }));
        seen.states.push(`${flow.flow}#${step.name}`);
        if (e.repeated) {
          seen.repeated ??= { keys: [], names: [] };
          addDistinct(seen.repeated.keys, e.repeated.keys);
          addDistinct(seen.repeated.names, e.repeated.names);
        }
      }
    }
  }
  return elements;
}

/** One C# class with a By per test id, sorted, with the recorded facts as doc comments. */
export function renderLocators(
  page: string,
  route: string,
  elements: Map<string, SeenElement>,
  names: Map<string, string>,
): string {
  const lines = [
    '// <auto-generated>',
    '//   Generated by web/tools/generate-locators from web/contracts. Do not edit.',
    '//   Change the React component + flow test, then regenerate.',
    '// </auto-generated>',
    'using OpenQA.Selenium;',
    'using CustomerPortal.Specs.Support;',
    '',
    'namespace CustomerPortal.Specs.Generated;',
    '',
    `public static class ${page}Locators`,
    '{',
    `    public const string Route = "${route}";`,
  ];
  for (const testId of [...elements.keys()].sort()) {
    const { info: e, states, repeated } = elements.get(testId)!;
    const member = names.get(testId)!;

    const facts = [`role=${e.role ?? '(none)'}`];
    if (!repeated) facts.push(`name="${e.name}"`);
    facts.push(`tag=${e.tag}`);
    if (e.portal) facts.push('PORTAL: rendered outside the component, search from document root');
    if (e.controls) facts.push(`controls=${e.controls}`);

    const seenIn = [...new Set(states)].sort();
    let remarks = `Seen in: ${seenIn.slice(0, 6).join(', ')}${seenIn.length > 6 ? ' …' : ''}`;
    if (repeated) {
      const keys = repeated.keys.map((k) => k || '(none)').join(', ');
      remarks = `Repeated; pick one by data-key or accessible name. Keys: ${keys}. Names: ${repeated.names.join(', ')}. ${remarks}`;
    }

    lines.push('', `    /// <summary>${facts.join('; ')}</summary>`, `    /// <remarks>${remarks}</remarks>`);
    if (repeated) {
      lines.push(`    public static readonly By ${member}s = By.CssSelector("[data-testid='${testId}']");`);
      lines.push(`    public static By ${member}(string key) => UiBy.TestIdWithKey("${testId}", key);`);
    } else {
      lines.push(`    public static readonly By ${member} = UiBy.TestId("${testId}");`);
    }
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function addDistinct<T>(target: T[], items: T[]) {
  for (const item of items) if (!target.includes(item)) target.push(item);
}
