// Generates Selenium locators and flow recipes for the tests project from the UI contracts.
//
// Deterministic on purpose: locators are facts copied from the rendered UI, so they
// are generated by code, not by an AI. The AI agent works one level up, mapping
// Gherkin steps to flows using the files written here.
//
//   npm run locators          # write ../tests/Generated/*
//   npm run locators:check    # CI: fail if stale or AC coverage gaps
import fs from 'node:fs';
import path from 'node:path';
import { GeneratorError, loadContracts } from './contracts';
import { collectElements, renderLocators } from './locators';
import { memberNames } from './naming';
import { renderRecipes } from './recipes';

const WEB_DIR = path.resolve(import.meta.dirname, '../..');
const CONTRACTS_DIR = path.join(WEB_DIR, 'contracts');
const TESTS_DIR = path.resolve(WEB_DIR, '../tests'); // the tests project sits next to web/
const OUT_DIR = path.join(TESTS_DIR, 'Generated');
const FEATURES_DIR = path.join(TESTS_DIR, 'Features');

try {
  process.exitCode = run(process.argv.includes('--check'));
} catch (e) {
  if (!(e instanceof GeneratorError)) throw e;
  console.error(e.message);
  process.exitCode = 1;
}

function run(check: boolean): number {
  if (!fs.existsSync(TESTS_DIR)) throw new GeneratorError(`Expected the tests project at ${TESTS_DIR}.`);

  // 1. Read contracts and render one locator class + one recipe file per page.
  const flows = loadContracts(CONTRACTS_DIR);
  const outputs = new Map<string, string>();
  for (const [page, pageFlows] of groupBy(flows, (f) => f.page)) {
    const routes = [...new Set(pageFlows.map((f) => f.route))];
    if (routes.length !== 1) throw new GeneratorError(`${page}: flows disagree on route ${routes.join(', ')}`);
    const elements = collectElements(pageFlows);
    const names = memberNames([...elements.keys()]);
    outputs.set(path.join(OUT_DIR, `${page}Locators.g.cs`), renderLocators(page, routes[0], elements, names));
    outputs.set(path.join(OUT_DIR, `${page}.recipes.md`), renderRecipes(page, pageFlows, names));
  }

  // 2. Recorder warnings (missing data-testid / data-key) are passed on.
  const warnings = flows.flatMap((f) =>
    f.steps.flatMap((s) => (s.type === 'state' ? s.warnings.map((w) => `${f.flow}#${s.name}: ${w}`) : [])),
  );
  const problems: string[] = [];

  // 3. Coverage: every @AC-nnn tag in the feature files needs a contract, and vice versa.
  const tags = featureTags();
  const covered = new Set(flows.flatMap((f) => f.acceptance));
  for (const ac of [...tags.keys()].sort())
    if (!covered.has(ac))
      problems.push(`${ac} (${tags.get(ac)!.join(', ')}) has no UI contract; ask the web developer for a flow test.`);
  for (const ac of [...covered].filter((ac) => !tags.has(ac)).sort())
    warnings.push(`${ac} has a UI contract but no scenario tagged @${ac}.`);

  // 4. Write the files, or (--check) only compare them with what is on disk.
  if (check) {
    for (const [file, text] of outputs)
      if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text)
        problems.push(`${relative(file)} is stale; run \`npm run locators\` in web/ and commit.`);
  } else {
    fs.mkdirSync(OUT_DIR, { recursive: true });
    for (const [file, text] of outputs) {
      fs.writeFileSync(file, text);
      console.log(`wrote ${relative(file)}`);
    }
  }

  for (const w of warnings) console.log(`warning: ${w}`);
  for (const p of problems) console.error(`error: ${p}`);
  const coveredTags = [...covered].filter((ac) => tags.has(ac)).length;
  console.log(`${flows.length} flows, ${coveredTags}/${tags.size} tagged acceptance criteria covered`);
  return problems.length > 0 ? 1 : 0;
}

/** @AC-nnn tag → the "file:line" places it appears, e.g. "Features/CustomerProfile.feature:12". */
function featureTags(): Map<string, string[]> {
  const tags = new Map<string, string[]>();
  if (!fs.existsSync(FEATURES_DIR)) return tags;
  const files = fs
    .readdirSync(FEATURES_DIR, { recursive: true, encoding: 'utf8' })
    .filter((f) => f.endsWith('.feature'))
    .sort();
  for (const file of files) {
    const lines = fs.readFileSync(path.join(FEATURES_DIR, file), 'utf8').split('\n');
    lines.forEach((line, i) => {
      for (const match of line.matchAll(/@(AC-\d+)\b/g)) {
        const where = tags.get(match[1]) ?? [];
        where.push(`${relative(path.join(FEATURES_DIR, file))}:${i + 1}`);
        tags.set(match[1], where);
      }
    });
  }
  return tags;
}

/** Path relative to tests/ with forward slashes, e.g. "Generated/CustomerProfileLocators.g.cs". */
function relative(file: string): string {
  return path.relative(TESTS_DIR, file).split(path.sep).join('/');
}

function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> {
  const groups = new Map<string, T[]>();
  for (const item of items) groups.set(key(item), [...(groups.get(key(item)) ?? []), item]);
  return groups;
}
