import type { Contract, Step, Target } from '../../src/testing/uiContract';

/** One numbered list per flow; targets are written as locator member names. */
export function renderRecipes(page: string, flows: Contract[], names: Map<string, string>): string {
  const lines = [
    `# ${page} flow recipes`,
    '',
    '<!-- Generated by web/tools/generate-locators from web/contracts. Do not edit. -->',
    '',
    'Each recipe is the exact interaction the web developer verified in a real browser.',
    `Member names refer to \`${page}Locators\`. Waits are observable conditions, never sleeps.`,
  ];
  for (const flow of flows) {
    lines.push(
      '',
      `## ${flow.flow}`,
      '',
      `- Acceptance: ${flow.acceptance.map((ac) => `@${ac}`).join(', ')}`,
      `- Route: \`${flow.route}\` · Fixture: \`${flow.fixture}\``,
      '',
    );
    flow.steps.forEach((step, i) => lines.push(`${i + 1}. ${describeStep(step, names)}`));
  }
  return lines.join('\n') + '\n';
}

function describeStep(s: Step, names: Map<string, string>): string {
  switch (s.type) {
    case 'state':
      return `_state_ **${s.name}** (\`${s.html}\`)${s.warnings.length > 0 ? ` ⚠ ${s.warnings.join('; ')}` : ''}`;
    case 'wait':
      return `wait until \`${targetRef(s.target, names)}\` is ${s.until}`;
    case 'action':
      if (s.action === 'reload') return 'reload the page';
      return `${s.action} \`${targetRef(s.target, names)}\`${s.text ? ` with "${s.text}"` : ''}`;
    case 'outcome': {
      // The recorder's own "visible" flag is implied by the wait before it.
      const expected = Object.entries(s.expect)
        .filter(([key]) => key !== 'visible')
        .map(([key, value]) => `${key}=${JSON.stringify(value)}`)
        .join(', ');
      return `**assert** \`${targetRef(s.target, names)}\` ${expected}`;
    }
  }
}

function targetRef(target: Target, names: Map<string, string>): string {
  if (!target.testId) return `/* no data-testid: role=${target.role ?? '(none)'} name="${target.name}" */`;
  const member = names.get(target.testId) ?? '?';
  return target.key ? `${member}("${target.key}")  // name "${target.name}"` : member;
}
